csharp = {
    'file_extensions': ['.cs'],
    'especial_characters': ['"', '{', '}', '(', ')', '->', '=', ';', ',', '\\\\', '\n'],
    'multline_start_start': '/*',
    'multline_start_end': '*/',
    'multline_start': ['/*', '*/'],
    'annotation_start_statement': '@',
    'end_declaration': ';',
    'keywords': ['abstract', 'as', 'base', 'bool',
                 'break', 'byte', 'case', 'catch',
                 'char', 'checked', 'class', 'const',
                 'continue', 'decimal', 'default', 'delegate',
                 'do', 'double', 'else', 'enum',
                 'event', 'explicit', 'extern', 'false',
                 'finally', 'fixed', 'float', 'for',
                 'foreach', 'goto', 'if', 'implicit',
                 'in', 'in', 'int', 'interface',
                 'internal', 'is', 'lock', 'long',
                 'namespace', 'new', 'null', 'object',
                 'operator', 'out', 'out', 'override',
                 'params', 'private', 'protected', 'public',
                 'readonly', 'ref', 'return', 'sbyte',
                 'sealed', 'short', 'sizeof', 'stackalloc',
                 'static', 'string', 'struct', 'switch',
                 'this', 'throw', 'true', 'try',
                 'typeof', 'uint', 'ulong', 'unchecked',
                 'unsafe', 'ushort', 'using', 'using', 'static',
                 'virtual', 'void', 'volatile', 'while'],
    'objetc_orientation': True,
    'strict_objetc_orientation': False,
    'has_lambda': False,
    'repos': [['https://github.com/shadowsocks/shadowsocks-windows', 'shadowsocks-windows'],
              ['https://github.com/CodeHubApp/CodeHub', 'CodeHub'],
              ['https://github.com/dotnet/corefx', 'corefx'],
              ['https://github.com/PowerShell/PowerShell', 'PowerShell'],
              ['https://github.com/dotnet/coreclr', 'coreclr'],
              ['https://github.com/dotnet/roslyn', 'roslyn'], ]
}

java = {
    'file_extensions': ['.java'],
    'end_declaration': ';',
    'annotation_start_statement': '@',
    'single_line_comment': "//",
    'multi_line__comment_start': "/*",
    'multi_line__comment_end': "*/",
    'especial_characters': ["//", "/*", '*/', '"', '{', '}', '(', ')', '->', '=', ';', ',', '\\', '\n'],
    'ignored_chars': [','],
    'loops_keywords': ['for', 'do', 'if', 'while', 'else'],
    'types': ['package', 'void', 'public', 'class', 'enum', 'float', 'int', 'short', 'interface', 'char', 'boolean', 'double', 'byte', 'long'],
    'modificadores': ['public', 'protected', 'default', 'synchronized', 'final', 'static', 'private', ],
    'keywords': [
        'abstract', 'continue', 'new', 'switch', 'assert',
        'goto', 'this', 'break', 'implements', 'throw', 'import', 'throws', 'case', 'instanceof', 'return',
        'transient', 'catch', 'extends', 'try', 'finally', 'strictfp', 'volatile', 'const', '', 'native', 'super'
    ],
    'objetc_orientation': False,
    'strict_objetc_orientation': True,
    'has_lambda': True,
    'repos': [
        ['https://github.com/ReactiveX/RxJava', 'RxJava'],
        ['https://github.com/elastic/elasticsearch', 'elasticsearch'],
        ['https://github.com/square/retrofit', 'retrofit'],
        ['https://github.com/google/guava', 'guava'],
        ['https://github.com/spring-projects/spring-boot', 'spring-boot'],
        ['https://github.com/PhilJay/MPAndroidChart', 'MPAndroidChart'],
    ],
}

javaScript = {
    'file_extensions': ['.js'],
    'especial_characters': ['//', '/*', '*/', '"', '{', '}', '(', ')', '->', '=', ';', ',', '\n'],
    'annotation_start_statement': '@',
    'keywords': [
        'abstract', 'arguments', 'await*', 'boolean',
        'break', 'byte', 'case', 'catch',
        'char', 'class*', 'const', 'continue',
        'debugger', 'default', 'delete', 'do',
        'double', 'else', 'enum*', 'eval',
        'export*', 'extends*', 'false', 'final',
        'finally', 'float', 'for', 'function',
        'goto', 'if', 'implements', 'import*',
        'in', 'instanceof', 'int', 'interface',
        'let*', 'long', 'native', 'new',
        'null', 'package', 'private', 'protected',
        'public', 'return', 'short', 'static',
        'super*', 'switch', 'synchronized', 'this',
        'throw', 'throws', 'transient', 'true',
        'try', 'typeof', 'var', 'void',
        'volatile', 'while', 'with', 'yield',
    ],
    'objetc_orientation': True,
    'strict_objetc_orientation': False,
    'has_lambda': True,
    'spagget_code': True,
    'repos': [
        ['https://github.com/d3/d3', 'd3'],
        ['https://github.com/vuejs/vue', 'vue'],
        ['https://github.com/freeCodeCamp/freeCodeCamp', 'freeCodeCamp'],
        ['https://github.com/facebook/react-native', 'react-native'],
        ['https://github.com/angular/angular.js', 'angular.js'],
        ['https://github.com/airbnb/javascript', 'javascript'],
    ]
}

shellscript = {
    'file_extensions': ['.shell', 'sh'],
    'especial_characters': ['//', '/*', '*/', '"', '{', '}', '(', ')', '->', '=', ';', ',', '\n'],
    'keywords': ['if', 'else', 'elif', 'then', 'fi', 'case', 'esac',
                 'for', 'select', 'while', 'until', 'do', 'done', 'in',
                 'function', 'time', '{', '}', '!', '[[', ']]', 'coproc'],
    'objetc_orientation': False,
    'strict_objetc_orientation': False,
    'has_lambda': False,
}

cplusplus = {
    'file_extension': ['.c', '.cpp', '.h'],
}
